# Generated by Django 3.2.11 on 2022-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('SENT', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменён')], default='CREATED', max_length=16),
        ),
    ]
